# Generated by Django 4.2.5 on 2024-01-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sofa', 'مبلمان'), ('curtains', 'پرده'), ('decoration', 'دکوراسیون')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('large_image', models.ImageField(upload_to='banners/index/large/', verbose_name='تصویر بزرگ')),
                ('small_image', models.ImageField(upload_to='banners/index/small/', verbose_name='تصویر کوچک')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرهای صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='SofaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sofa', 'مبلمان'), ('sofafabric', 'پارچه مبلی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('small_image', models.ImageField(upload_to='banners/sofa/small/', verbose_name='تصویر کوچک')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرهای صفحه مبل',
            },
        ),
        migrations.CreateModel(
            name='LargeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/sofa/large/', verbose_name='تصویر بزرگ')),
                ('sofa_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_images', to='website.sofabanner')),
            ],
        ),
    ]
