# Generated by Django 4.2.5 on 2024-01-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeSofaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/sofa/large/', verbose_name='تصویر بزرگ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sofabanner',
            options={'verbose_name': 'بنر مبل', 'verbose_name_plural': 'بنرهای صفحه مبل'},
        ),
        migrations.RemoveField(
            model_name='sofabanner',
            name='category',
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='small_fabric_image',
            field=models.ImageField(default=5, upload_to='banners/sofa/fabric/small/', verbose_name='تصویر کوچک پارچه مبلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='sofa_category',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='sofa_banners', to='website.indexbanner', verbose_name='دسته\u200cبندی مبل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sofabanner',
            name='small_image',
            field=models.ImageField(upload_to='banners/sofa/small/', verbose_name='تصویر کوچک مبل'),
        ),
        migrations.DeleteModel(
            name='LargeImage',
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='large_images',
            field=models.ManyToManyField(related_name='sofa_banners', to='website.largesofaimage', verbose_name='تصاویر بزرگ'),
        ),
    ]
