# Generated by Django 4.2.5 on 2024-01-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_largesofaimage_alter_sofabanner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofabanner',
            name='sofa_category',
        ),
    ]
