# Generated by Django 4.2.5 on 2024-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_sofabanner_sofa_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sofabanner',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنرهای صفحه مبل'},
        ),
        migrations.RenameField(
            model_name='sofabanner',
            old_name='small_image',
            new_name='small_sofa_image',
        ),
        migrations.RemoveField(
            model_name='sofabanner',
            name='large_images',
        ),
        migrations.RemoveField(
            model_name='sofabanner',
            name='small_fabric_image',
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='large_sofa_image_1',
            field=models.ImageField(default=5, upload_to='banners/sofa/large/', verbose_name=' 1 تصویر بزرگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='large_sofa_image_2',
            field=models.ImageField(default=9, upload_to='banners/sofa/large/', verbose_name=' 2 تصویر بزرگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='large_sofa_image_3',
            field=models.ImageField(default=52, upload_to='banners/sofa/large/', verbose_name=' 3 تصویر بزرگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofabanner',
            name='small_sofafabric_image',
            field=models.ImageField(default=7, upload_to='banners/sofafabric/small/', verbose_name='تصویر کوچک پارچه مبلی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LargeSofaImage',
        ),
    ]
