# Generated by Django 4.2.5 on 2024-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_length_orderitem_needs_curtain_rod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='needs_curtain_rod',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
