# Generated by Django 4.2.5 on 2024-01-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_needs_curtain_rod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
