# Generated by Django 4.2.5 on 2024-02-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_gordeh_orderitem_miane_orderitem_scouti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Gordeh',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Miane',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Scouti',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Tasho',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cornice_7',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cornice_9',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='glue_10kg',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='glue_4kg',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='needs_curtain_rod',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='number_of_panels',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='width',
        ),
        migrations.CreateModel(
            name='Cornice',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('cornice_7', models.BooleanField(blank=True, default=False, null=True)),
                ('cornice_9', models.BooleanField(blank=True, default=False, null=True)),
                ('Gordeh', models.BooleanField(blank=True, default=False, null=True)),
                ('Miane', models.BooleanField(blank=True, default=False, null=True)),
                ('Tasho', models.BooleanField(blank=True, default=False, null=True)),
                ('Scouti', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='Customcurtain',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('number_of_panels', models.PositiveIntegerField(blank=True, null=True)),
                ('needs_curtain_rod', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='Floorcoverings',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('glue_4kg', models.BooleanField(blank=True, default=False, null=True)),
                ('glue_10kg', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('orders.orderitem',),
        ),
    ]
