# Generated by Django 4.2.5 on 2024-02-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cornice_gordeh_alter_cornice_miane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcurtain',
            name='number_of_panels',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customcurtain',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='floorcoverings',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Gordeh',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='گرده'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Miane',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='میانه'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Scouti',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اسکوتی'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Tasho',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تاشو'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='cornice_7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کورنیس ۷'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='cornice_9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کورنیس ۹'),
        ),
        migrations.AlterField(
            model_name='customcurtain',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='طول'),
        ),
        migrations.AlterField(
            model_name='customcurtain',
            name='needs_curtain_rod',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نیاز به تعویض کرکره'),
        ),
        migrations.AlterField(
            model_name='customcurtain',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='floorcoverings',
            name='glue_10kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='چسب ۱۰ کیلوگرم'),
        ),
        migrations.AlterField(
            model_name='floorcoverings',
            name='glue_4kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='چسب ۴ کیلوگرم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='texture_code',
            field=models.IntegerField(verbose_name='کد تکسچر'),
        ),
        migrations.CreateModel(
            name='NormalProducts',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
            ],
            bases=('orders.orderitem',),
        ),
    ]
