# Generated by Django 4.2.5 on 2024-01-18 12:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='CorniceSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('7', '7 سانتی'), ('9', '9 سانتی')], max_length=2, verbose_name='سایز')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'سایز قرنیز',
                'verbose_name_plural': 'انتخاب سایزهای قرنیز',
            },
        ),
        migrations.CreateModel(
            name='CorniceSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(choices=[('Gordeh', 'گرده'), ('Miane', 'میانه'), ('Nobshi', 'نبشی'), ('Tasho', 'تاشو'), ('Tasme', 'تسمه'), ('Lab_pelle', 'لب پله'), ('Scouti', 'اسکوتی'), ('Meet', 'میت')], max_length=15, verbose_name='لوازم قرنیز')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'لوازم قرنیز',
                'verbose_name_plural': 'لوازم قرنیزها',
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_unit', models.CharField(blank=True, choices=[('meter', 'متر'), ('millimeter', 'میلیمتر'), ('centimeter', 'سانتیمتر'), ('inch', 'اینچ')], default='meter', max_length=13, null=True, verbose_name='واحد اندازه گیری طول')),
                ('length', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='طول')),
                ('width_unit', models.CharField(blank=True, choices=[('meter', 'متر'), ('millimeter', 'میلیمتر'), ('centimeter', 'سانتیمتر'), ('inch', 'اینچ')], default='meter', max_length=13, null=True, verbose_name='واحد اندازه گیری عرض')),
                ('width', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='عرض')),
                ('thickness_unit', models.CharField(blank=True, choices=[('meter', 'متر'), ('millimeter', 'میلیمتر'), ('centimeter', 'سانتیمتر'), ('inch', 'اینچ')], default='millimeter', max_length=13, null=True, verbose_name='واحد اندازه گیری ضخامت')),
                ('thickness', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='ضخامت')),
            ],
        ),
        migrations.CreateModel(
            name='Glue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('10kg', 'ده کیلویی'), ('4kg', 'چهار کیلویی')], max_length=10, verbose_name='نوع چسب')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'چسب',
                'verbose_name_plural': 'چسب ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='تصویر')),
                ('image_number', models.PositiveIntegerField(verbose_name='شماره تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Square_meters', 'متر مربع'), ('roll', 'رول'), ('Branch', 'شاخه'), ('number', 'عدد')], default='number', max_length=13, verbose_name='واحد قیمت')),
                ('price_wholesale', models.IntegerField(verbose_name='قیمت عمده')),
                ('price_retail', models.IntegerField(verbose_name='قیمت خرده')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product_code', models.CharField(max_length=3, verbose_name='کد محصول')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='نام دسته')),
                ('dimensions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_dimensions', to='products.dimensions', verbose_name='ابعاد')),
                ('images', models.ManyToManyField(related_name='products', to='products.image', verbose_name='تصاویر')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_price', to='products.price', verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'همه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد تکسچر')),
                ('image', models.ImageField(upload_to='texture_images/', verbose_name='تصویر تکسچر')),
            ],
            options={
                'verbose_name': 'تصویر تکسچر',
                'verbose_name_plural': 'تصاویر تکسچر ها',
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'پرده',
                'verbose_name_plural': 'پرده\u200cها',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'دکراسیون',
                'verbose_name_plural': 'دکراسیون',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Sofafabric',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'پارچه مبل',
                'verbose_name_plural': 'پارچه\u200cهای مبلی',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='textures',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.texture', verbose_name='تکسچرها'),
        ),
        migrations.CreateModel(
            name='Cornice',
            fields=[
                ('decoration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.decoration')),
            ],
            options={
                'verbose_name': 'قرنیز',
                'verbose_name_plural': 'قرنیزها',
            },
            bases=('products.decoration',),
        ),
        migrations.CreateModel(
            name='Customcurtain',
            fields=[
                ('curtain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.curtain')),
                ('curtain_rod', models.BooleanField(default=False, verbose_name='چوب پرده')),
                ('curtain_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل پرده')),
                ('side_fabric', models.CharField(blank=True, max_length=50, null=True, verbose_name='پارچه کنار')),
            ],
            options={
                'verbose_name': 'پرده سفارشی',
                'verbose_name_plural': 'پرده\u200cهای سفارشی',
            },
            bases=('products.curtain',),
        ),
        migrations.CreateModel(
            name='Floorcoverings',
            fields=[
                ('decoration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.decoration')),
            ],
            options={
                'verbose_name': 'پوشش کف',
                'verbose_name_plural': 'پوشش\u200cهای کف',
            },
            bases=('products.decoration',),
        ),
        migrations.CreateModel(
            name='Readycurtain',
            fields=[
                ('curtain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.curtain')),
                ('curtain_rod', models.BooleanField(default=False, verbose_name='چوب پرده')),
            ],
            options={
                'verbose_name': 'پرده آماده',
                'verbose_name_plural': 'پرده\u200cهای آماده',
            },
            bases=('products.curtain',),
        ),
        migrations.CreateModel(
            name='Wallcoverings',
            fields=[
                ('decoration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.decoration')),
            ],
            options={
                'verbose_name': 'پوشش دیواری',
                'verbose_name_plural': 'پوشش\u200cهای دیواری',
            },
            bases=('products.decoration',),
        ),
        migrations.CreateModel(
            name='Zebracurtain',
            fields=[
                ('curtain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.curtain')),
            ],
            options={
                'verbose_name': 'پرده زبرا',
                'verbose_name_plural': 'پرده\u200cهای زبرا',
            },
            bases=('products.curtain',),
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('Fabrictype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sofas', to='products.sofafabric', verbose_name='نوع پارچه')),
                ('accessory', models.ManyToManyField(blank=True, related_name='accessories', to='products.product', verbose_name='اکسسوری')),
            ],
            options={
                'verbose_name': 'مبل',
                'verbose_name_plural': 'مبل\u200cها',
            },
            bases=('products.product',),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date_created'], name='products_pr_date_cr_729cc8_idx'),
        ),
        migrations.AddField(
            model_name='floorcoverings',
            name='glue',
            field=models.ManyToManyField(related_name='Glue', to='products.glue', verbose_name='انتخاب چسب'),
        ),
        migrations.AddField(
            model_name='customcurtain',
            name='accessory',
            field=models.ManyToManyField(blank=True, related_name='Customcurtain_accessories', to='products.product', verbose_name='اکسسوری'),
        ),
        migrations.AddField(
            model_name='cornice',
            name='cornicesize',
            field=models.ManyToManyField(related_name='cornices', to='products.cornicesize', verbose_name='سایز قرنیز'),
        ),
        migrations.AddField(
            model_name='cornice',
            name='cornicesupply',
            field=models.ManyToManyField(related_name='cornices', to='products.cornicesupply', verbose_name='لوازم قرنیز'),
        ),
    ]
