# Generated by Django 4.2.5 on 2024-01-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cornicesize_price_remove_cornicesupply_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornicesize',
            name='price_retail',
        ),
        migrations.RemoveField(
            model_name='cornicesize',
            name='price_wholesale',
        ),
        migrations.RemoveField(
            model_name='cornicesupply',
            name='price_retail',
        ),
        migrations.RemoveField(
            model_name='cornicesupply',
            name='price_wholesale',
        ),
        migrations.AddField(
            model_name='cornicesize',
            name='price',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='corniceSize_price', to='products.price', verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cornicesupply',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corniceSupply_price', to='products.price', verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
