# Generated by Django 4.2.5 on 2024-01-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornicesupply',
            name='supply',
            field=models.CharField(choices=[('Gordeh', '(پایان کار) گرده'), ('Miane', 'میانه'), ('Tasho', 'تاشو'), ('Scouti', 'اسکوتیا')], max_length=15, verbose_name='لوازم قرنیز'),
        ),
        migrations.CreateModel(
            name='curtain_rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtain_rod_price', to='products.price', verbose_name='قیمت')),
            ],
        ),
        migrations.AlterField(
            model_name='customcurtain',
            name='curtain_rod',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.curtain_rod', verbose_name='چوب پرده'),
        ),
    ]
