# Generated by Django 4.2.5 on 2024-02-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cornicesupply_supply_curtain_rod_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorniceSize',
            new_name='CorniceType',
        ),
        migrations.AlterModelOptions(
            name='cornicetype',
            options={'verbose_name': 'نوع قرنیز', 'verbose_name_plural': 'انتخاب سایزهای قرنیز'},
        ),
        migrations.RenameField(
            model_name='cornice',
            old_name='cornicesize',
            new_name='CorniceType',
        ),
    ]
