# Generated by Django 4.2.5 on 2024-02-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_cornicesize_cornicetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornice',
            name='CorniceType',
        ),
        migrations.AddField(
            model_name='cornice',
            name='CorniceType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cornicesType', to='products.cornicetype', verbose_name='نوع قرنیز'),
            preserve_default=False,
        ),
    ]
