# Generated by Django 4.2.5 on 2024-02-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_cornice_cornicetype_cornice_cornicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornice',
            name='CorniceType',
        ),
        migrations.AddField(
            model_name='cornice',
            name='Cornic_7',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cornices_7', to='products.cornicetype', verbose_name='قرنیز 7 سانتی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cornice',
            name='Cornice_9',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='cornices_9', to='products.cornicetype', verbose_name='قرنیز 9 سانتی'),
            preserve_default=False,
        ),
    ]
