# Generated by Django 4.2.5 on 2024-02-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cornice_cornicetype_cornice_cornic_7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornicetype',
            name='size',
        ),
    ]
