# Generated by Django 4.2.5 on 2024-02-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_cornicetype_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cornice',
            old_name='Cornice_9',
            new_name='Cornic_9',
        ),
    ]
