# Generated by Django 4.2.5 on 2024-02-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_cornice_9_cornice_cornic_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcurtain',
            name='curtain_rod',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.price', verbose_name='چوب پرده'),
        ),
        migrations.DeleteModel(
            name='curtain_rod',
        ),
    ]
