# Generated by Django 4.2.5 on 2024-02-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_customcurtain_curtain_rod_delete_curtain_rod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorcoverings',
            name='glue',
        ),
        migrations.AddField(
            model_name='floorcoverings',
            name='glue_10kg',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='glue_10kg', to='products.price', verbose_name='چسب 10 کیلویی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorcoverings',
            name='glue_4kg',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='glue_4kg', to='products.price', verbose_name='چسب 4 کیلویی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Glue',
        ),
    ]
