# Generated by Django 4.2.5 on 2024-02-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_floorcoverings_glue_floorcoverings_glue_10kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornice',
            name='Cornic_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cornices_7', to='products.price', verbose_name='قرنیز 7 سانتی'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Cornic_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cornices_9', to='products.price', verbose_name='قرنیز 9 سانتی'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Gordeh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gordeh', to='products.price', verbose_name='(پایان کار) گرده'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Miane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Miane', to='products.price', verbose_name='میانه'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Scouti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scouti', to='products.price', verbose_name='اسکوتیا'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='Tasho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tasho', to='products.price', verbose_name='تاشو'),
        ),
        migrations.AlterField(
            model_name='floorcoverings',
            name='glue_10kg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glue_10kg', to='products.price', verbose_name='چسب 10 کیلویی'),
        ),
        migrations.AlterField(
            model_name='floorcoverings',
            name='glue_4kg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glue_4kg', to='products.price', verbose_name='چسب 4 کیلویی'),
        ),
    ]
